spring:
  application:
    name: evcare-backend
    url: ${SPRING_BACKEND_URL:http://localhost:8080}
  profiles:
    active: dev

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/userinfo.email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-name: Google

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        from: ${SPRING_MAIL_USERNAME}
        from-name: ${SPRING_MAIL_FROM_NAME:EVcare Support}
        debug: ${SPRING_MAIL_DEBUG:false}
        smtp:
          auth: ${SPRING_MAIL_SMTP_AUTH:true}
          starttls:
            enable: true
            required: true
          ssl:
            enable: ${SPRING_MAIL_SMTP_SSL_ENABLE:false}
# Frontend URL for OAuth2 redirect
frontend:
  url: ${FRONTEND_URL:http://localhost:5000}

server:
  port: 8080

# JWT Configuration
jwt:
  signer-key: ${JWT_SIGNER_KEY}

payment:
  vnpay:
    tmn-code: ${VNPAY_TMN_CODE:test_tmn_code}
    hash-secret: ${VNPAY_HASH_SECRET:test_hash_secret}
    url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    return-url: "{baseUrl}/api/v1/vnpay/payment-return"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
